Form/Type/FeedbackType.php
<?php
/**
 * File containing the FeedbackType class.
 *
 * @copyright Copyright (C) eZ Systems AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 * @version //autogentag//
 */
namespace EzSystems\DemoBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FeedbackType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName', 'text')
            ->add('lastName', 'text')
            ->add('email', 'email')
            ->add('subject', 'text')
            ->add('country', 'country')
            ->add('message', 'textarea')
            ->add('save', 'submit');
    }

    public function getName()
    {
        return 'ezdemo_feedback';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array('data_class' => 'EzSystems\DemoBundle\Entity\Feedback'));
    }
}

Resources/views/fields/ezauthor_simple.html.twig
{# This is a simple ezauthor field type template implementation with comma separation between author names #}
{% block ezauthor_field %}
{% spaceless %}
    {% for author in field.value.authors %}
        {{ author.name }}{% if not loop.last %}, {% endif %}
    {% endfor %}
{% endspaceless %}
{% endblock %}

Resources/views/fields/ezbinaryfile_video.html.twig
{# Extending base content_fields.html.twig to be able to access other blocks, like "field_attributes" #}
{% extends "EzPublishCoreBundle::content_fields.html.twig" %}

{# BinaryFile that contains a video and that we want to display as HTML5 video. #}
{% block ezbinaryfile_field %}
    {% set videoType = parameters.videoType|default( "video/mp4" ) %}
    {% set controls = parameters.controls|default( true ) %}
    {% set preload = parameters.preload|default( "auto" ) %}
    {% set width = parameters.width|default( 330 ) %}
    {% set height = parameters.height|default( 264 ) %}
    {% set poster = parameters.poster|default( "" ) %}
    <video{% if controls %} controls{% endif %} preload="{{ preload }}" width="{{ width }}" height="{{ height }}" poster="{{ poster }}" {{ block( "field_attributes" ) }}>
        <source src="{{ path( ez_route( 'ez_content_download', { 'content': content, 'fieldIdentifier': 'file' } ) ) }}" type="{{ videoType }}" />
    </video>
{% endblock %}

Resources/views/fields/ezimage_simple.html.twig
{# This field accepts the following parameters:
    - alias (image variation name). Defaults to "original" (e.g. image originally uploaded)
    - field / versionInfo / parameters are additional variables passed to every field template block. See EzPublishCodeBundle::content_fields_html.twig
 #}
{% block ezimage_field %}
    {% if not ez_is_field_empty( content, field ) %}
        {% set image_alt = parameters.alt|default( field.value.alternativeText ) %}
        {% set image_alias = ez_image_alias( field, versionInfo, parameters.alias|default( 'original' ) ) %}
        {# if image alias is not found, null is returned, an error is added in logs and the image is not displayed #}
        {% if image_alias %}
            <img src="{{ asset( image_alias.uri ) }}"{% if imageAlias.width is defined %} width="{{ image_alias.width }}"{% endif %}{% if imageAlias.height is defined %} height="{{ image_alias.height }}"{% endif %}{% if image_alt is not empty %} alt="{{ image_alt }}"{% endif %} class="img-responsive" />
        {% endif %}
    {% endif %}
{% endblock %}

Resources/views/fields/ezobjectrelation_image.html.twig
{% block ezobjectrelation_field %}
    {% spaceless %}
        {% if not ez_is_field_empty( content, field ) %}
            <div {{ block( 'field_attributes' ) }}>
                {{ render( controller( 'ez_content:viewContent', {
                    'contentId': field.value.destinationContentId,
                    'viewType': 'relation',
                    'params': {
                        'parameters': parameters
                    }
                    } )
                ) }}
            </div>
        {% endif %}
    {% endspaceless %}
{% endblock %}